name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ http://13.233.145.68 }}
          username: ubuntu
          key: ${{ ssh -i "MyPortfolio.pem" ubuntu@ec2-13-233-145-68.ap-south-1.compute.amazonaws.com }}
          source: "dist/*"
          target: "/home/ubuntu/MyPortfolio"